### PR TITLE
update to django 1.10 / sticky footer / nicer event list

### PR DESCRIPTION
**Pull request by Visgean**
1. I have upgraded the project so it would be able to run on django 1.10
2. I have set the footer to stick to the bottom of the page as it looks much better 
3. I have deleted the line " There are no events arranged in the near future. " this is confusing as it implies that there are no events planned even though the line above it says that there are events every 4th tuesday. 
4. I have removed django bootstrap because it is obsolete and did not do much anyway. 
5. I have upgraded django markdown to different pip package as the original one is no longer maintained and does not support django 1.10

### CODE REVIEW

**Comment by d0ugal** [comment]
Django 1.1? It already uses 1.10 :) https://github.com/python-edinburgh/pythonedinburgh/blob/master/requirements/_base.txt#L1

**Comment by Visgean** [comment]
I highly doubt that. Thats seems like a requirement that was not updated, otherwise the site would fail as there is no function ``django.conf.urls.patterns``. I tried to run the project with fresh virtualenv and fixed all errors on the run.

**Comment by Visgean** [comment]
the test for the merge of 1.10 failed https://travis-ci.org/python-edinburgh/pythonedinburgh/builds/187254730

**Comment by d0ugal** [comment]
okay, so it probably was running Django 1.8 before. https://github.com/python-edinburgh/pythonedinburgh/commit/830d8e9856f9792ac327ef29939060fea655ed42#diff-43c69fd3bae9536e8d1948d7d52b53da

**Comment by d0ugal** [comment]
Changed look decent but you need @judy2k to look into it as I think he is the only one with the power to deploy changes anyway...

**Comment by Visgean** [comment]
@judy2k ?

**Pull request closed without merging**
